### PR TITLE
Update xdma_mod.c

### PR DESCRIPTION
**Pull request by riggy2013**
build on CentOS 8.3 will generate error:

XDMA/linux-kernel/xdma/xdma_mod.c:301:2: error: implicit declaration of function ??pci_cleanup_aer_uncorrect_error_status?? [-Werror=implicit-function-declaration]
  pci_cleanup_aer_uncorrect_error_status(pdev);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:316: /home/ndam/Downloads/dma_ip_drivers-master/XDMA/linux-kernel/xdma/xdma_mod.o] Error 1

The reason is, name change from pci_cleanup_aer_uncorrect_error_status() to pci_aer_clear_nonfatal_status() at https://github.com/torvalds/linux/commit/894020fdd88c1e9a74c60b67c0f19f1c7696ba2f

CentOS and RedHat 8.3 accepted the patch.

### CODE REVIEW

**Comment by jberaud** [comment]
Legitimate, but to be more consistent I would use the same structure as here:

https://github.com/Xilinx/dma_ip_drivers/blob/master/XDMA/linux-kernel/xdma/libxdma.h#L36

>CentOS and RedHat 8.3 accepted the patch.

I would say "backported" the patch :-)

**Comment by jberaud** [comment]
@riggy2013 Thanks! Ok for me (history could be reworked before merging but I'll leave that to the persons actually doing the merge).
(I am no Xilinx developer).

**Review by jberaud — APPROVED** [review]
